on:
  youtube:
    channel_id:
      - UCoSrY_IQQVpmIRZ9Xf-y93g
jobs:
  webhook:
    name: Send HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://notify-api.line.me/api/notify
          method: 'POST'
          headers: '{ "Authorization": "Bearer Qshih7atOJTO3wkEOV8G2WRAHx68FwL5nwV81G6Yxsc" }'
          body: ${{on.youtube.outputs.title}} ${{on.youtube.outputs.description}} ${{on.youtube.outputs.link}}
